version: '2.0'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - ./postgresql-init:/docker-entrypoint-initdb.d
